### PR TITLE
Add a CONTRIBUTING file.

### PR DESCRIPTION
**Pull request by treshugart**

### CODE REVIEW

**Comment by treshugart** [comment]
Ahh, just saw this in `./docs/contributing.md`. For better compatibility with open source projects, should we be using `./CONTRIBUTING.md` instead? Happy to merge these two, either way.

**Comment by ryanbraganza** [comment]
> Ahh, just saw this in `./docs/contributing.md`. For better compatibility with open source projects, should we be using `./CONTRIBUTING.md` instead? Happy to merge these two, either way.

I think we want to keep the docs/contributing.md file around so that it still generates a page on the site https://brisk-docs.netlify.com/docs/contributing/

Maybe we could use the root CONTRIBUTING.md file as the source of truth, and make docs/contributing simply a transclude of the root file?

**Comment by treshugart** [comment]
> Maybe we could use the root CONTRIBUTING.md file as the source of truth, and make docs/contributing simply a transclude of the root file?

That's sort of what I was thinking. Happy to do that as part of this.

**Comment by Noviny** [comment]
Hello!

Just thinking about this - this link won't work on the website. Can we remove it from the readme.md

**Pull request closed without merging**
